Update run 6 hours.yml

diff --git a/.github/workflows/run 6 hours.yml b/.github/workflows/run 6 hours.yml
--- a/.github/workflows/run 6 hours.yml
+++ b/.github/workflows/run 6 hours.yml
@@ -2,7 +2,7 @@ name: Run Every 6Hrs
 
 on:
   schedule:
-    - cron: '30 00,6,12,18 * * *'  # Runs at 01:30, 07:30, 13:30, and 19:30 UTC
+    - cron: '30 0,6,12,18 * * *'  # Runs at 01:30, 07:30, 13:30, and 19:30 UTC
 
 jobs:
   generate-plot:
@@ -10,20 +10,26 @@ jobs:
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Set up Python
-        uses: actions/setup-python@v2
+        uses: actions/setup-python@v4
         with:
-          python-version: 3.9
+          python-version: '3.9'
 
       - name: Upgrade Pip
         run: pip install --upgrade pip
 
       - name: Install Dependencies
-        run: pip install matplotlib pandas ftputil requests pillow bytesbufio
+        run: |
+          pip install -r requirements.txt
 
       - name: Run TC Scripts
         run: |
+          set -e  # Fail fast on errors
+          python tc_io.py
           python tc_wp.py
           python tc_al.py
+          python tc_ep.py
+          python tc_cp.py
+          python tc_sh.py
